-- Wave 1 seed: fictional SoCal events for Overdrive + EventDiscovery.
-- All rows: approved, published, manual source. Dates are relative to now().

truncate table events restart identity cascade;

-- ── Overdrive (10) ──────────────────────────────────────────────────────────

insert into events (
  experience, overdrive_category, title, description,
  starts_at, ends_at, timezone, venue_name, address,
  is_free, price_amount, price_currency,
  latitude, longitude, source_type, moderation_status, publication_status, event_status, organizer_name
) values
(
  'overdrive', 'car_meet',
  'Canyon Crest Cars & Coffee',
  'Casual morning meetup for daily drivers and weekend builds. No burnouts, keep it neighbor-friendly.',
  now() + interval '2 days' + interval '8 hours',
  now() + interval '2 days' + interval '11 hours',
  'America/Los_Angeles',
  'Crestview Lot B',
  '1200 Erringer Rd, Simi Valley, CA',
  true, null, 'USD',
  34.2694, -118.7815,
  'manual', 'approved', 'published', 'scheduled',
  'Valley Motoring Club'
),
(
  'overdrive', 'car_show',
  'Thousand Oaks Classic Showcase',
  'Judged classic and restomod showcase with family-friendly viewing lanes.',
  now() + interval '5 days' + interval '10 hours',
  now() + interval '5 days' + interval '16 hours',
  'America/Los_Angeles',
  'Oak Park Green',
  '100 N Moorpark Rd, Thousand Oaks, CA',
  false, 15.00, 'USD',
  34.1706, -118.8376,
  'manual', 'approved', 'published', 'scheduled',
  'Conejo Classic Collective'
),
(
  'overdrive', 'drive_cruise',
  'Pacific Ribbon Evening Cruise',
  'Guided coastal cruise with two scenic pull-offs. Street-legal vehicles only.',
  now() + interval '3 days' + interval '17 hours',
  now() + interval '3 days' + interval '20 hours',
  'America/Los_Angeles',
  'Malibu Bluffs Meet Point',
  '24250 Pacific Coast Hwy, Malibu, CA',
  false, 25.00, 'USD',
  34.0335, -118.6919,
  'manual', 'approved', 'published', 'scheduled',
  'PCH Drivers Guild'
),
(
  'overdrive', 'autocross',
  'Simi Valley Parking Lot Autocross',
  'Timed cone course for beginners and intermediate drivers. Helmets required.',
  now() + interval '8 days' + interval '9 hours',
  now() + interval '8 days' + interval '15 hours',
  'America/Los_Angeles',
  'Westfield Overflow Lot',
  '1555 Simi Town Center Way, Simi Valley, CA',
  false, 45.00, 'USD',
  34.2850, -118.7970,
  'manual', 'approved', 'published', 'scheduled',
  'Cone Runners SoCal'
),
(
  'overdrive', 'track_event',
  'Willow-Adjacent Track Day Preview',
  'Open lapping orientation day with instructor-led sessions for first-timers.',
  now() + interval '12 days' + interval '7 hours',
  now() + interval '12 days' + interval '16 hours',
  'America/Los_Angeles',
  'High Desert Motorsports Staging',
  'Near Rosamond, CA',
  false, 199.00, 'USD',
  34.8640, -118.1630,
  'manual', 'approved', 'published', 'scheduled',
  'Apex Prep Events'
),
(
  'overdrive', 'car_meet',
  'Santa Monica Night Owls Meet',
  'Low-key evening gather for modified street cars near the pier district.',
  now() + interval '1 day' + interval '19 hours',
  now() + interval '1 day' + interval '22 hours',
  'America/Los_Angeles',
  'Ocean View Lot',
  '1550 Ocean Ave, Santa Monica, CA',
  true, null, 'USD',
  34.0100, -118.4960,
  'manual', 'approved', 'published', 'scheduled',
  'Night Owls SM'
),
(
  'overdrive', 'car_show',
  'Arts District Rolling Sculpture',
  'Curated downtown display of concept builds and custom interiors.',
  now() + interval '6 days' + interval '11 hours',
  now() + interval '6 days' + interval '17 hours',
  'America/Los_Angeles',
  'Warehouse Row Courtyard',
  '800 E Traction Ave, Los Angeles, CA',
  false, null, 'USD',
  34.0407, -118.2340,
  'manual', 'approved', 'published', 'scheduled',
  'DTLA Garage Society'
),
(
  'overdrive', 'drive_cruise',
  'Pasadena Foothill Sunday Drive',
  'Relaxed foothill loop with coffee stop. Pace cars lead at posted limits.',
  now() + interval '4 days' + interval '9 hours',
  now() + interval '4 days' + interval '13 hours',
  'America/Los_Angeles',
  'Memorial Park Meet',
  '85 E Holly St, Pasadena, CA',
  true, null, 'USD',
  34.1478, -118.1445,
  'manual', 'approved', 'published', 'scheduled',
  'Foothill Drivers'
),
(
  'overdrive', 'other',
  'EV Conversion Workshop Night',
  'Hands-on talks on DIY EV conversions, battery safety, and shop tooling.',
  now() + interval '9 days' + interval '18 hours',
  now() + interval '9 days' + interval '21 hours',
  'America/Los_Angeles',
  'Northridge Maker Hall',
  '9301 Reseda Blvd, Northridge, CA',
  false, 10.00, 'USD',
  34.2350, -118.5360,
  'manual', 'approved', 'published', 'scheduled',
  'Volt Bench Collective'
),
(
  'overdrive', 'autocross',
  'Pasadena Twilight Solo Practice',
  'Practice-only autocross evening. No championship points.',
  now() + interval '7 days' + interval '17 hours',
  now() + interval '7 days' + interval '21 hours',
  'America/Los_Angeles',
  'Rose Bowl Outer Lot',
  '1001 Rose Bowl Dr, Pasadena, CA',
  false, null, 'USD',
  34.1610, -118.1670,
  'manual', 'approved', 'published', 'scheduled',
  'Solo Practice Group'
);

-- ── EventDiscovery (15) ─────────────────────────────────────────────────────

insert into events (
  experience, event_discovery_category, title, description,
  starts_at, ends_at, timezone, venue_name, address,
  is_free, price_amount, price_currency,
  latitude, longitude, source_type, moderation_status, publication_status, event_status, organizer_name
) values
(
  'event_discovery', 'family',
  'Simi Valley Story Picnic',
  'Outdoor storytime and craft tables for kids and caregivers.',
  now() + interval '2 days' + interval '10 hours',
  now() + interval '2 days' + interval '12 hours',
  'America/Los_Angeles',
  'Rancho Park Lawn',
  '1379 E Los Angeles Ave, Simi Valley, CA',
  true, null, 'USD',
  34.2710, -118.7340,
  'manual', 'approved', 'published', 'scheduled',
  'Neighborhood Pages'
),
(
  'event_discovery', 'community',
  'Thousand Oaks Block Swap',
  'Community swap meet for household goods, books, and plants.',
  now() + interval '3 days' + interval '9 hours',
  now() + interval '3 days' + interval '14 hours',
  'America/Los_Angeles',
  'Civic Arts Plaza Plaza',
  '2100 E Thousand Oaks Blvd, Thousand Oaks, CA',
  true, null, 'USD',
  34.1750, -118.8490,
  'manual', 'approved', 'published', 'scheduled',
  'Conejo Neighbors'
),
(
  'event_discovery', 'arts_and_culture',
  'Malibu Shoreline Sketch Walk',
  'Guided plein-air sketching along the bluffs. All skill levels welcome.',
  now() + interval '4 days' + interval '15 hours',
  now() + interval '4 days' + interval '18 hours',
  'America/Los_Angeles',
  'Bluffside Overlook',
  '24201 Civic Center Way, Malibu, CA',
  false, 12.00, 'USD',
  34.0358, -118.6890,
  'manual', 'approved', 'published', 'scheduled',
  'Coastline Arts Circle'
),
(
  'event_discovery', 'outdoor',
  'Santa Monica Sunrise Yoga',
  'Beach-adjacent morning yoga. Bring your own mat.',
  now() + interval '1 day' + interval '6 hours',
  now() + interval '1 day' + interval '7 hours',
  'America/Los_Angeles',
  'Beach Path Stage',
  '200 Santa Monica Pier, Santa Monica, CA',
  true, null, 'USD',
  34.0095, -118.4970,
  'manual', 'approved', 'published', 'scheduled',
  'Tide & Breath'
),
(
  'event_discovery', 'food_and_markets',
  'DTLA Evening Market Alley',
  'Pop-up food stalls featuring local makers and dessert carts.',
  now() + interval '5 days' + interval '17 hours',
  now() + interval '5 days' + interval '21 hours',
  'America/Los_Angeles',
  'Little Tokyo Side Street',
  '300 E 2nd St, Los Angeles, CA',
  false, 5.00, 'USD',
  34.0475, -118.2390,
  'manual', 'approved', 'published', 'scheduled',
  'Alley Eats Collective'
),
(
  'event_discovery', 'entertainment',
  'Pasadena Courtyard Comedy Night',
  'Stand-up showcase with three local comics. Outdoor seating.',
  now() + interval '6 days' + interval '19 hours',
  now() + interval '6 days' + interval '21 hours',
  'America/Los_Angeles',
  'Colorado Courtyard',
  '40 N Mentor Ave, Pasadena, CA',
  false, 18.00, 'USD',
  34.1460, -118.1320,
  'manual', 'approved', 'published', 'scheduled',
  'Laugh Line Productions'
),
(
  'event_discovery', 'educational',
  'Northridge Home Compost Clinic',
  'Learn backyard composting setups that fit apartment and yard living.',
  now() + interval '7 days' + interval '11 hours',
  now() + interval '7 days' + interval '13 hours',
  'America/Los_Angeles',
  'Community Learning Room',
  '18300 Lemarsh St, Northridge, CA',
  true, null, 'USD',
  34.2385, -118.5320,
  'manual', 'approved', 'published', 'scheduled',
  'Green Habit Lab'
),
(
  'event_discovery', 'family',
  'Pasadena Mini Makers Fair',
  'Hands-on STEM tables for ages 5–12 with take-home mini projects.',
  now() + interval '8 days' + interval '10 hours',
  now() + interval '8 days' + interval '14 hours',
  'America/Los_Angeles',
  'Central Library Annex',
  '285 E Walnut St, Pasadena, CA',
  false, 8.00, 'USD',
  34.1495, -118.1440,
  'manual', 'approved', 'published', 'scheduled',
  'Spark Bench Kids'
),
(
  'event_discovery', 'community',
  'Echo Park Volunteer Clean Sweep',
  'Neighborhood litter pickup with supplies provided. Meet at the boathouse path.',
  now() + interval '3 days' + interval '8 hours',
  now() + interval '3 days' + interval '11 hours',
  'America/Los_Angeles',
  'Echo Park Lake Path',
  '751 Echo Park Ave, Los Angeles, CA',
  true, null, 'USD',
  34.0780, -118.2600,
  'manual', 'approved', 'published', 'scheduled',
  'Lake Loop Volunteers'
),
(
  'event_discovery', 'arts_and_culture',
  'Arts District Open Studio Loop',
  'Self-guided studio hop featuring printmakers and ceramic artists.',
  now() + interval '10 days' + interval '12 hours',
  now() + interval '10 days' + interval '18 hours',
  'America/Los_Angeles',
  'Arts District Welcome Desk',
  '777 S Alameda St, Los Angeles, CA',
  false, null, 'USD',
  34.0360, -118.2315,
  'manual', 'approved', 'published', 'scheduled',
  'Studio Loop LA'
),
(
  'event_discovery', 'outdoor',
  'Griffith Twilight Trail Social',
  'Easy paced group hike with city-view pause. Flashlights recommended.',
  now() + interval '4 days' + interval '18 hours',
  now() + interval '4 days' + interval '20 hours',
  'America/Los_Angeles',
  'Western Canyon Trailhead',
  '4730 Crystal Springs Dr, Los Angeles, CA',
  true, null, 'USD',
  34.1230, -118.3000,
  'manual', 'approved', 'published', 'scheduled',
  'Hillside Walkers'
),
(
  'event_discovery', 'food_and_markets',
  'Ventura Blvd Night Bites Crawl',
  'Ticketed tasting stamps across five participating pop-ups.',
  now() + interval '9 days' + interval '18 hours',
  now() + interval '9 days' + interval '21 hours',
  'America/Los_Angeles',
  'Studio City Starter Stop',
  '12100 Ventura Blvd, Studio City, CA',
  false, 35.00, 'USD',
  34.1435, -118.3960,
  'manual', 'approved', 'published', 'scheduled',
  'Bite Map Nights'
),
(
  'event_discovery', 'entertainment',
  'Santa Monica Silent Film Lawn',
  'Outdoor silent film with live piano accompaniment.',
  now() + interval '11 days' + interval '19 hours',
  now() + interval '11 days' + interval '21 hours',
  'America/Los_Angeles',
  'Reed Park Lawn',
  '1133 7th St, Santa Monica, CA',
  false, 12.00, 'USD',
  34.0210, -118.4900,
  'manual', 'approved', 'published', 'scheduled',
  'Reel Lawn Society'
),
(
  'event_discovery', 'educational',
  'Malibu Tidepool Steward Talk',
  'Naturalist-led talk on tidepool etiquette and coastal wildlife.',
  now() + interval '6 days' + interval '9 hours',
  now() + interval '6 days' + interval '11 hours',
  'America/Los_Angeles',
  'Leo Carrillo Education Deck',
  '35000 Pacific Coast Hwy, Malibu, CA',
  true, null, 'USD',
  34.0445, -118.9330,
  'manual', 'approved', 'published', 'scheduled',
  'Shore Stewards'
),
(
  'event_discovery', 'community',
  'Glendale Pocket Park Concert',
  'Acoustic afternoon set from local musicians. Blankets welcome.',
  now() + interval '5 days' + interval '15 hours',
  now() + interval '5 days' + interval '17 hours',
  'America/Los_Angeles',
  'Pacific Park Pocket Green',
  '101 Pacific Ave, Glendale, CA',
  false, null, 'USD',
  34.1460, -118.2550,
  'manual', 'approved', 'published', 'scheduled',
  'Pocket Park Music'
);
